name: release

on:
  push:
    tags:
      - "*"
      
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
          
      - name: Build jar
        run: make build
        
      - run: make init
        name: Install npm FHIR packages

      - name: Build standalone projects
        run: make build-stanadlone-projects node_modules="node_modules/" zrc="zrc/standalone_projects/"
      - name: Build terminologies
        run: make build-terminology-bundles
        env:
          ICD_10_CLIENT_ID: ${{ secrets.ICD_10_CLIENT_ID }}
          ICD_10_CLIENT_SECRET: ${{ secret.ICD_10_CLIENT_SECRET }}
          LOINC_LOGIN: ${{ secret.LOINC_LOGIN }}
          LOINC_PASSWORD: ${{ secret.LOINC_PASSWORD }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/zen-fhir-${{ env.RELEASE_VERSION }}-standalone.jar, zrc/standalone_projects/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload private terminologies
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          glob: '*.zip'
          destination: hs-zen-terminologies/
